version: "3"

services:
  base: &base
    image: golang:1.14-alpine3.11
    volumes:
      - ./:/golanglab:cached

  queueworker:
    <<: *base
    working_dir: /golanglab/queueworker
    command: >
      sh -c '
        go build -o bin
        ./bin
      '
  api:
    <<: *base
    working_dir: /golanglab/api
    ports:
      - "8080:8080"
    command: >
      sh -c '
        go build -o bin
        ./bin
      '


  dicontainer:
    <<: *base
    working_dir: /golanglab/dicontainer
    ports:
      - "8080:8080"
    command: >
      sh -c '
        go build -o bin
        ./bin
      '

  lint:
    image: golangci/golangci-lint
    working_dir: /golanglab
    volumes:
      - ./:/golanglab:cached
    command:
      sh -c '
        golangci-lint run
      '

  mockdb:
    <<: *base
    working_dir: /golanglab/mockdb
    command: >
      sh -c '
        go test .
      '
    depends_on:
      - postgresql

  postgresql:
    image: postgres:10.5
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
