version: "3"

services:
  base: &base
    image: golang:1.14-alpine3.11
    volumes:
      - ./:/golanglab:cached

  queueworker: &queueworker
    <<: *base
    working_dir: /golanglab/queueworker
    command: >
      sh -c '
        go build -o bin
        ./bin
      '
  api: &api
    <<: *base
    working_dir: /golanglab/api
    ports:
      - "8080:8080"
    command: >
      sh -c '
        go build -o bin
        ./bin
      '

